version: 2
updates:
  # Maintain dependencies for Ruby gems
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "monthly"
    rebase-strategy: "auto"
    open-pull-requests-limit: 20
