version: 2
updates:
  # Maintain dependencies for Ruby gems
  - package-ecosystem: 'bundler'
    directory: '/'
    schedule:
      interval: 'weekly'
    rebase-strategy: 'auto'
    open-pull-requests-limit: 20
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
